apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-db
  namespace: mogambo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-db
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
        - name: catalogue-db
          image: mohamedadel9988/catalogue-db:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "fake_password"
            - name: MYSQL_DATABASE
              value: "socksdb"
            - name: MYSQL_USER
              value: "catalogue_user"
            - name: MYSQL_PASSWORD
              value: "default_password"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  namespace: mogambo
spec:
  selector:
    app: catalogue-db
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
